- job-template:
    name: 'ops-hw-config-check-{platform}'
    node: openswitch

    wrappers:
        - build-timeout:
            timeout: 120

    builders:
        - revoke-sudo
        - commit-message-validation:
            module: 'ops-hw-config'
        - module-build-branch:
            module: 'ops-hw-config'
            platform: '{platform}'

- job-template:
    name: 'ops-hw-config-gate-{platform}'
    node: openswitch

    wrappers:
        - build-timeout:
            timeout: 180

    builders:
        - revoke-sudo
        - module-build-branch:
            module: 'ops-hw-config'
            platform: '{platform}'

    publishers:
        - conditional-junit
        - conditional-htmlreports
- job-group:
    name: 'ops-hw-config-jobs'
    jobs:
      - 'ops-hw-config-check-{platform}'
      - 'ops-hw-config-gate-{platform}'
