- job-template:
    name: 'ops-config-yaml-check-{platform}'
    node: openswitch
    wrappers:
        - build-timeout:
            timeout: 120
    builders:
        - revoke-sudo
        - commit-message-validation:
            module: 'ops-config-yaml'
        - module-build-branch:
            module: 'ops-config-yaml'
            platform: '{platform}'
    publishers:
        - post-ws-clean

- job-template:
    name: 'ops-config-yaml-gate-{platform}'
    node: vsi

    wrappers:
        - build-timeout:
            timeout: 180

    builders:
        - module-build-branch:
            module: 'ops-config-yaml'
            platform: '{platform}'
        - check-docker-state
        - clear-test-logs
        - module-test:
            module: 'ops-config-yaml'
            platform: '{platform}'

    publishers:
        - conditional-gather-test-results
        - conditional-htmlreports
        - archive-syslog
        - archive-test-logs-on-failure
        - post-ws-clean

- job-group:
    name: 'ops-config-yaml-jobs'
    jobs:
      - 'ops-config-yaml-check-{platform}'
      - 'ops-config-yaml-gate-{platform}'
